spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related PROD APIs"
  contactDetails:
    name: "Roberto Cuccurese - Developer"
    email: "roberto.cuccurese@eazybank.com"
  onCallSupport:
    - (081) 4832934
    - (+39) 3459785234