services:
  accounts:
    image: "rcuccurese/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rcuccurese
  loans:
    image: "rcuccurese/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rcuccurese
  cards:
    image: "rcuccurese/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rcuccurese
networks:
  rcuccurese:
    driver: "bridge"