spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related PROD APIs"
  contactDetails:
    name: "Alessandro Cuccurese - QA Lead"
    email: "alessandro.cuccurese@eazybank.com"
  onCallSupport:
    - (089) 4836788
    - (+39) 3335687900