build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank accounts related PROD APIs"
  contactDetails:
    name: "Loredana Cuccurese - Product Owner"
    email: "loredana.cuccurese@eazybank.com"
  onCallSupport:
    - (031) 7563421
    - (+39) 3357623567