build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Alessandro Cuccurese - QA Lead"
    email: "alessandro.cuccurese@eazybank.com"
  onCallSupport:
    - (089) 4836788
    - (+39) 3335687900